# ----------- CONFIGURABLE START -----------
title:            "Marvel: Play as Naruto at the beginning "
description:      ""
baseurl:     "MPNAB"
url:              "" # Site url, without a slash at the end.
signoff:          "lord-asgord" # Your name
facebook_appid:   # APP ID for like button, remove from /_includes/share.html if unwanted.
google_analytics: # Set tracking, remove from /javascripts/basic.js if unwanted.
share:            false # Turn on twitter and facebook share buttons

links:
  - name:         Chapters
    url:          /
    external:     false
  - name:         About
    url:          /about
    external:     false
  - name:         YFT Home
    url:          https://yourfantasytranslations.github.io
    external:     true
# ------------ CONFIGURABLE END ------------

permalink:        /posts/:title
defaults:
  - values:
      layout: "default"